## R code to run CFA models on datasets generated from a 3-class LCA (see GenData_MixSim.R)
## This script runs CFA models using an external Monte Carlo analysis implemented by Mplus,
## as well as  runs the individual replications and stores the results of readModels() for more detailed
## model diagnostics
## Author: Michael Hallquist
## Last Updated: 31 Oct 2017

## It is necessary to set the working directory if you are not working from the Rstudio project
#setwd("/path/to/directory/containing/simulation/R/scripts")

## Define directory to store all results, both Mplus outputs and RData structures containing parsed results
inputdir <- "~/mplus_tmp/data" #location to "data" folder, the root of replication files created by GenData_MixSim.R

## outputdir <- "data/cfa_montecarlo_results" #can be relative to basedir
outputdir <- "~/mplus_tmp/cfa_outputs" #or can be absolute

## ensure that the destination directory is created
dir.create(outputdir, showWarnings = FALSE, recursive=TRUE)

## location of Mplus executable to be called by runModels
## Mplus_command <- "/Users/mnh5174/Applications/Mplus/Mplus"
Mplus_command <- "/Applications/Mplus/mplus"

library(MplusAutomation)
library(foreach)
library(doSNOW)

## You can control how many replications are estimated here.
## By default, GenData_MixSim.R generates 1000 replications per condition.
## This variable defines how many replications are fit below
replications <- 1:10

##1) write out mplus datasets and list
##2) run external monte carlo analysis for FMM and CFA
##3) read in and save results

## This worker function generates Mplus syntax for a single replication in the code below.
## One could easily adapt it to use mplusObject and mplusModeler
getSyntax <- function(nc, nv, ss, sep, np, dataSection, output=NULL, savedata=NULL, processors=1) {
  syntax <- paste0(
    "TITLE:\n",
    "  CFA NClass = ", nc, ", NVar = ", nv, ", NCases = ", ss, ", LCSep = ", sep, ", NoiseProp = ", np, "\n",
    dataSection,
    "VARIABLE:\n",
    "  NAMES ARE ", paste0("x", 1:nv, collapse=" "), " trueclas;\n",
    "  USEVARIABLES ARE ", paste0("x", 1:nv, collapse=" "), ";\n",
    "ANALYSIS:\n",
    "  TYPE = GENERAL;\n",
    "  ESTIMATOR=MLR;\n",
    "  PROCESSORS=", processors, " 1;\n",
    "  ITERATIONS = 2000;\n",
    "  SDITERATIONS = 50;\n",
    "  MITERATIONS = 2000;\n",
    "MODEL:\n",
    "  fac BY ", paste0("x1-x", nv, "*1"), ";\n",
    "  fac@1; !fix var to 1 for identification\n",
    "  [", paste0("x1-x", nv, "*0"), "];\n", #zero means by default
    "\n",
    output,
    savedata
  )
  return(syntax)
}


##Load a list of all models to be run (generated by GenData_MixSim.R)
load(file.path(inputdir, "cfaMasterList.RData"))

## The number of parallel threads to execute
njobs <- 8
setDefaultClusterOptions(master="localhost")
clusterobj <- makeSOCKcluster(njobs)
registerDoSNOW(clusterobj)

## Use foreach to estimate models in parallel
## Note that we estimate models within tempdir(), which should be a unique directory for each R worker process
fmm <- foreach(m=iter(cfalist), .inorder=FALSE, .multicombine=TRUE, .packages=c("MplusAutomation")) %dopar% {
  ## do not re-estimate replications that have already completed
  if (file.exists(file.path(outputdir, m$fname_resultsRData))) {
    cat("Already processed replications:", m$fname_resultsRData, "\n")
    return(NULL) #next
  }
  
  ## verify that replications object exists (generated by GenData_MixSim.R)
  if (!file.exists(file.path(inputdir, m$fname_sourceReps))) {
    cat("Cannot open replications file: ", file.path(inputdir, m$fname_sourceReps), "\n")
    return(NULL) #next
  }
  
  ## load replications dataset
  load(file=file.path(inputdir, m$fname_sourceReps))
  
  ## 1) Run external Monte Carlo in Mplus, which integrates results across replications
  ## define data section for external Monte Carlo
  dataSection <- paste0(
    "DATA:\n",
    "  FILE=external_montecarlo_list.dat;\n",
    "  TYPE=MONTECARLO;\n"
  )
  
  ## include tech1 and tech9 in output for external Monte Carlo
  outputSection <- paste0(
    "OUTPUT:\n",
    "  TECH1 TECH9;\n"
  )   
  
  ## write Monte Carlo syntax to file
  cat(getSyntax(m$nc, m$nv, m$ss, m$sep, m$np, dataSection=dataSection, output=outputSection), file=file.path(tempdir(), "external_montecarlo.inp"))
  
  ## write each replication dataset and the list of datasets to file
  datList <- c()
  for (i in 1:min(length(fmm_sim), max(replications))) {
    dat <- cbind(fmm_sim[[i]]$X, fmm_sim[[i]]$id)
    write.table(dat, file=file.path(tempdir(), paste0("external_montecarlo_rep", sprintf("%04d", i), ".dat")), row.names=FALSE, col.names=FALSE)
    datList <- c(datList, paste0("external_montecarlo_rep", sprintf("%04d", i), ".dat"))
  }
  write.table(datList, file=file.path(tempdir(), "external_montecarlo_list.dat"), row.names=FALSE, col.names=FALSE, quote=FALSE)
  
  ## run external monte carlo through Mplus
  runModels(file.path(tempdir(), "external_montecarlo.inp"), recursive=FALSE, logFile=NULL, Mplus_command = Mplus_command)
  
  ## read in monte carlo results
  monteCarloCombined <- readModels(file.path(tempdir(), "external_montecarlo.out"))
  
  ##move input and output files to results directory. rename uniquely based on cell in simulation design
  file.rename(
    file.path(tempdir(), "external_montecarlo.inp"), 
    file.path(outputdir, paste0("cfa_n", m$ss, "_p", gsub(".", "_", m$np*100, fixed=TRUE), "_s", gsub(".", "_", m$sep, fixed=TRUE), "_c", m$nc, "_v", m$nv, ".inp"))
  )
  
  file.rename(
    file.path(tempdir(), "external_montecarlo.out"), 
    file.path(outputdir, paste0("cfa_n", m$ss, "_p", gsub(".", "_", m$np*100, fixed=TRUE), "_s", gsub(".", "_", m$sep, fixed=TRUE), "_c", m$nc, "_v", m$nv, ".out"))
  )
  
  ## 2) now run models for each replication individually and collate the results into a list
  ## save class probabilities for each run
  savedata <- paste0("SAVEDATA:\n",
                     "  FILE=fscores.dat;\n",
                     "  SAVE=FSCORES;\n")
  
  ## Add tech1 output to each replication
  outputSection <- paste0(
    "OUTPUT:\n",
    "  TECH1;\n"
  )
  
  ## loop over individual replications and run each using runModels and readModels
  repResults <- list()
  for (i in 1:min(length(fmm_sim), max(replications))) {
    ##specify the replication dataset to be used
    dataSection <- paste0(
      "DATA:\n",
      "  FILE=external_montecarlo_rep", sprintf("%04d", i), ".dat;\n"
    )
    
    cat(getSyntax(m$nc, m$nv, m$ss, m$sep, m$np, dataSection=dataSection, output=outputSection, savedata=savedata), file=file.path(tempdir(), "individual_rep.inp")) #create syntax for replication
    runModels(file.path(tempdir(), "individual_rep.inp"), recursive=FALSE, logFile=NULL, Mplus_command = Mplus_command) #run replication
    repResults[[i]] <- readModels(file.path(tempdir(), "individual_rep.out")) #read replication results
  }
  
  ##add simulation parameters to replication list object for clarity
  attr(repResults, "n") <- m$ss  #sample size
  attr(repResults, "p") <- m$np  #noise proportion
  attr(repResults, "s") <- m$sep #latent separation
  attr(repResults, "c") <- m$nc  #number of true classes
  attr(repResults, "v") <- m$nv  #number of variables
  
  ## save all results for this cell in the simulation design to an .RData file
  save(repResults, monteCarloCombined, file=file.path(outputdir, m$fname_resultsRData), compress="xz", compression_level=9)
  
  ##cleanup temporary files
  unlink(c(
    file.path(tempdir(), "external_montecarlo_rep*.dat"),
    file.path(tempdir(), "*.tst"), #sometimes left behind by Mplus
    file.path(tempdir(), "external_montecarlo_rep*.dat"),
    file.path(tempdir(), "external_montecarlo_list.dat"),
    file.path(tempdir(), "individual_rep.inp"),
    file.path(tempdir(), "individual_rep.out"),
    file.path(tempdir(), "fscores.dat")
  ))
  
  return(m$fname_sourceReps)
}

## Shutdown parallel cluster
stopCluster(clusterobj)
